name: CI

on:
  pull_request:

  group: "tests-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  run_starlark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Kurtosis
        uses: ./.github/actions/kurtosis-install
      - name: Run basic test
        run: |
          kurtosis run ${{ github.workspace }} --args-file configs/just-network.json

  run_with_args:
    strategy:
      matrix:
        file_name:
          [
            "./configs/just-network.json",
            "./configs/one-chain.json",
            "./configs/two-chains-with-bridge.json",
            "./configs/hypersdk.json",
            "./configs/fuji.json",
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Kurtosis
        uses: ./.github/actions/kurtosis-install
      - name: Run Starlark
        run: |
          kurtosis run ${{ github.workspace }} --args-file ${{ matrix.file_name }}
